%{
#include <stdio.h>
extern int tokenvalue;
%}
%start document
%token NEWLINE NUMBER ASSIGNMENT OPENING_BRACKET CLOSING_BRACKET OPENING_BLOCK CLOSING_BLOCK INPUT_BLOCK OUTPUT_BLOCK AUTOMAT_DECLARATION STATE_DECLARATION CONDITION NEGATION TRANSITION
%%
document	:
		;

